apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: fulfillment-service
rules:
  - apiGroups:
      - cloudkit.openshift.io
    resources:
      - clusterorders
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - hypershift.openshift.io
    resources:
      - hostedclusters
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - ''
    resources:
      - secrets
    verbs:
      - get
      - list
      - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: fulfillment-service
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: fulfillment-service
subjects:
  - kind: ServiceAccount
    name: fulfillment-service
    namespace: cloudkit-operator-system
